schema: "classroom50/repo-config/v1"
classroom: "agi"
assignment: "github-pages"
owner:
  username: "Ksj09"
  id: 218925459
  accepted_at: "2026-09-02T00:19:00Z"
source:
  owner: "gsm-class"
  owner_id: 318515310
  repo: "github-pages"
  branch: "main"
